"""
Translate a list of Rule objects into rt_rewrite.conf text.

The grammar generated against here is read directly from
extensions/rt_rewrite/rt_rewrite_conf.y (not guessed, not paraphrased from the sample doc):

    rules:    | rules add | rules if_ add | rules drop | rules if_ drop
              | rules map | rules if_ map | rules variable ;

    add:      ADD '=' command '/' add_avp_part '=' add_value ';'
    drop:     DROP '=' drop_part ';'
    map:      MAP '=' source_part '>' dest_part ';'
    variable: VARIABLE QSTRING '=' variable_part ';'
    if_:      IF QSTRING <op> QSTRING            (op in < <= = >= >)

Where *_part / *_avp_part are colon-separated QSTRING paths (for descending into Grouped AVPs),
and every QSTRING is a double-quoted string.

Each rule gets AT MOST one IF clause (the grammar does not support combining several conditions
on one statement -- `if_` is singular in every `rules` alternative above). A rule with a
condition needs a VARIABLE declared for the AVP path being compared; this module deduplicates
identical variable_avp_path values across rules so the same VARIABLE is declared once and reused,
rather than emitting a fresh (and, per the grammar, invalid --  VARIABLE names must be distinct)
declaration per rule.
"""

from typing import List

from models import Rule, RuleType


def _qpath(path: List[str]) -> str:
    """Render a list of AVP names as a colon-separated list of quoted strings, e.g.
    ["Service-Information", "IMS-Information"] -> '"Service-Information" : "IMS-Information"'.
    """
    return " : ".join(f'"{_escape(p)}"' for p in path)


def _escape(value: str) -> str:
    """rt_rewrite_conf.l's QSTRING token is `\"[^\"\\n]*\"` (see ard_conf.l / rt_rewrite's own
    lexer, which follows the exact same pattern as every other Flex/Bison config parser in this
    codebase): a double-quoted string that cannot itself contain a `"` or a newline. There is no
    escape sequence support, so the only thing we can safely do with a value containing one of
    those characters is refuse it -- silently mangling it would generate a config that either
    fails to parse or, worse, parses into something other than what the operator intended.
    """
    if ('"' in value) or ("\n" in value):
        raise ValueError(f"Value {value!r} contains a double-quote or newline, which the "
                          f"rt_rewrite config format cannot represent")
    return value


def generate_config(rules: List[Rule]) -> str:
    """Build the full rt_rewrite.conf text for the given rules. Disabled rules are skipped
    entirely (not commented out -- rt_rewrite's grammar has no comment-out-a-statement concept
    beyond the whole-line `#` the lexer treats as a comment, and we'd rather not rely on that
    for correctness)."""
    active = [r for r in rules if r.enabled]

    # Assign one VARIABLE name per distinct condition AVP path, in first-seen order.
    var_names: dict = {}
    for r in active:
        if r.condition:
            key = tuple(r.condition.variable_avp_path)
            if key not in var_names:
                var_names[key] = f"cond{len(var_names) + 1}"

    lines: List[str] = []

    lines.append("# Generated by webui -- do not edit by hand, changes will be overwritten")
    lines.append("# on the next Apply. Edit the rules through the web interface instead.")
    lines.append("")

    if var_names:
        for path, name in var_names.items():
            lines.append(f'VARIABLE "{_escape(name)}" = {_qpath(list(path))};')
        lines.append("")

    for r in active:
        prefix = ""
        if r.condition:
            var_name = var_names[tuple(r.condition.variable_avp_path)]
            prefix = f'IF "{var_name}" {r.condition.operator} "{_escape(r.condition.value)}" '

        if r.type == RuleType.MOVE:
            lines.append(f"{prefix}MAP = {_qpath(r.source_avp_path)} > {_qpath(r.dest_avp_path)};")
        elif r.type == RuleType.DELETE:
            lines.append(f"{prefix}DROP = {_qpath(r.source_avp_path)};")
        elif r.type == RuleType.ADD:
            lines.append(
                f'{prefix}ADD = "{_escape(r.command_name)}" / {_qpath(r.dest_avp_path)} '
                f'= "{_escape(r.value)}";'
            )
        else:
            raise ValueError(f"Unknown rule type: {r.type}")

    return "\n".join(lines) + "\n"
