/*
 * app_dea : Phase 3 -- interconnect policy enforcement and fraud detection for messages FROM
 * external peers.
 *
 * Both checks below only fire for requests whose sending peer is not one of the configured
 * internal_realm(s) (see dea_fwd_req in dea_hiding.c, which computes from_internal once and
 * gates both dea_check_interconnect and dea_check_fraud on !from_internal) -- traffic that
 * originates inside our own trusted network is never subject to interconnect policy.
 *
 * Rejection idiom: both functions follow the same in-place request -> error-answer conversion
 * used by app_redirect and rt_rewrite: fd_msg_new_answer_from_req() mutates *msg into its own
 * answer, fd_msg_rescode_set() fills in the Result-Code (and, with type_id=1, our own real
 * Origin-Host/Origin-Realm -- safe to show as-is here, since this answer is generated by the DEA
 * itself using its own public-facing identity, not relayed from an internal node), fd_msg_send()
 * sends it and sets *msg to NULL. Per fd_rt_fwd_register's documented contract ("[the callback]
 * may also choose to handle the message in a more complex form. In that case, it must set *msg =
 * NULL ... In such case, the forwarding thread will stop processing this message"), returning
 * with *rejected = 1 after this tells the caller (dea_fwd_req) to stop immediately.
 */

#include "app_dea.h"

/* Turn *msg into an error answer and send it. On success, *msg is NULL on return (per
 * fd_msg_send's contract) and the caller must not touch it again. DIAMETER_AUTHORIZATION_REJECTED
 * is used uniformly for both policy violations below (rather than a more specific code like
 * DIAMETER_APPLICATION_UNSUPPORTED) so an external peer probing our interconnect policy cannot
 * distinguish "wrong Application-Id" from "spoofed realm" from the error code alone. */
static int reject_request(struct msg ** msg, char * reason)
{
	TRACE_DEBUG(INFO, "app_dea: rejecting a request from an external peer: %s", reason);

	CHECK_FCT( fd_msg_new_answer_from_req(fd_g_config->cnf_dict, msg, MSGFL_ANSW_ERROR) );
	CHECK_FCT( fd_msg_rescode_set(*msg, "DIAMETER_AUTHORIZATION_REJECTED", reason, NULL, 1) );
	CHECK_FCT( fd_msg_send(msg, NULL, NULL) );

	return 0;
}

/* Find the interconnect_realm rule matching `realm`, if any. */
static struct dea_interconnect_rule * find_rule(uint8_t * realm, size_t realmlen)
{
	struct fd_list * li;

	for (li = dea_conf->interconnect_rules.next; li != &dea_conf->interconnect_rules; li = li->next) {
		struct dea_interconnect_rule * r = li->o;
		if (fd_os_almostcasesrch(realm, realmlen, r->realm, r->realmlen, NULL) == 0)
			return r;
	}
	return NULL;
}

int dea_check_interconnect(struct msg ** msg, int * rejected)
{
	struct avp * avp;
	struct avp_hdr * ahdr = NULL;
	struct msg_hdr * hdr;
	struct dea_interconnect_rule * rule;
	struct fd_list * li;
	int allowed;

	*rejected = 0;

	if (FD_IS_LIST_EMPTY(&dea_conf->interconnect_rules))
		return 0; /* feature not configured: no restriction */

	CHECK_FCT( fd_msg_search_avp(*msg, dea_avp_origin_realm, &avp) );
	if (avp) {
		CHECK_FCT( fd_msg_avp_hdr(avp, &ahdr) );
	}
	if (!avp || !ahdr->avp_value) {
		/* No Origin-Realm to check against a policy that requires one: fail safe by
		 * rejecting, rather than silently letting an unidentifiable peer through once this
		 * feature is active. */
		*rejected = 1;
		return reject_request(msg, "Missing or unparsed Origin-Realm");
	}

	rule = find_rule(ahdr->avp_value->os.data, ahdr->avp_value->os.len);
	if (!rule) {
		/* No rule for this realm at all: default-deny, see file header and README. */
		*rejected = 1;
		dea_stats_inc(DEA_STAT_INTERCONNECT_REJECTED_NO_RULE);
		return reject_request(msg, "No interconnect agreement configured for this realm");
	}

	CHECK_FCT( fd_msg_hdr(*msg, &hdr) );

	allowed = 0;
	for (li = rule->allowed_apps.next; li != &rule->allowed_apps; li = li->next) {
		struct dea_app_id * a = li->o;
		if (a->id == hdr->msg_appl) {
			allowed = 1;
			break;
		}
	}

	if (!allowed) {
		*rejected = 1;
		dea_stats_inc(DEA_STAT_INTERCONNECT_REJECTED_APP);
		return reject_request(msg, "Application-Id not permitted for this realm");
	}

	dea_stats_inc(DEA_STAT_INTERCONNECT_ALLOWED);
	return 0;
}

int dea_check_fraud(struct msg ** msg, int * rejected)
{
	DiamId_t src_id;
	size_t src_idlen;
	struct peer_hdr * peer = NULL;
	struct avp * avp;
	struct avp_hdr * ahdr;

	*rejected = 0;

	if (!dea_conf->fraud_check_realm_consistency)
		return 0;

	CHECK_FCT( fd_msg_source_get(*msg, &src_id, &src_idlen) );
	if (!src_id)
		return 0; /* no known source peer for this message (e.g. locally originated) */

	CHECK_FCT( fd_peer_getbyid(src_id, src_idlen, 0, &peer) );
	if (!peer || !peer->info.runtime.pir_realm || !peer->info.runtime.pir_realmlen)
		return 0; /* peer unknown, or did not report a realm at CER/CEA: nothing to compare against */

	CHECK_FCT( fd_msg_search_avp(*msg, dea_avp_origin_realm, &avp) );
	if (!avp)
		return 0;
	CHECK_FCT( fd_msg_avp_hdr(avp, &ahdr) );
	if (!ahdr->avp_value)
		return 0;

	if (fd_os_almostcasesrch(ahdr->avp_value->os.data, ahdr->avp_value->os.len,
			(uint8_t *) peer->info.runtime.pir_realm, peer->info.runtime.pir_realmlen, NULL) == 0)
		return 0; /* consistent: the peer is sending a message for the realm it presented at connection time */

	dea_stats_inc(DEA_STAT_FRAUD_MISMATCH_DETECTED);

	fd_log_error("app_dea: FRAUD SUSPECT -- peer '%s' (CER/CEA realm '%.*s') sent a request "
		"claiming Origin-Realm '%.*s' -- %s",
		src_id,
		(int)peer->info.runtime.pir_realmlen, peer->info.runtime.pir_realm,
		(int)ahdr->avp_value->os.len, ahdr->avp_value->os.data,
		dea_conf->fraud_reject_on_mismatch ? "rejecting" : "logging only (fraud_reject_on_mismatch is off)");

	if (dea_conf->fraud_reject_on_mismatch) {
		*rejected = 1;
		dea_stats_inc(DEA_STAT_FRAUD_REJECTED);
		return reject_request(msg, "Origin-Realm does not match the realm presented at connection time");
	}

	return 0;
}
