Identity = "dea1.test.local";
Realm = "test.local";

TLS_Cred = "/etc/ssl/certs/freeDiameter.pem", "/etc/ssl/private/freeDiameter.key";
TLS_CA = "/etc/ssl/certs/freeDiameter.pem";

LoadExtension = "/FreeDiameter-DRA_generic/freeDiameter-custom-DEA-DRA/build/extensions/dict_nasreq.fdx";
LoadExtension = "/FreeDiameter-DRA_generic/freeDiameter-custom-DEA-DRA/build/extensions/dict_dcca.fdx";
LoadExtension = "/FreeDiameter-DRA_generic/freeDiameter-custom-DEA-DRA/build/extensions/dict_dcca_3gpp.fdx";
LoadExtension = "/FreeDiameter-DRA_generic/freeDiameter-custom-DEA-DRA/build/extensions/app_dea.fdx" : "/etc/freeDiameter/app_dea.conf";
LoadExtension = "/FreeDiameter-DRA_generic/freeDiameter-custom-DEA-DRA/build/extensions/rt_rewrite.fdx" : "/etc/freeDiameter/rt_rewrite.conf";
